name: My personal blog - Oleksandr Olashyn
email: oleksandr@dancingwithcrm.com
permalink: ':title/'
title: Dancing with CRM
description: Oleksandr's Olashyn personal blog about Power Platform, Dynamics 365 and many more

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.dancingwithcrm.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Oleksandr Olashyn # add your name
author-pic: face-min.jpg
author-pic-full: face.jpg
about-author: My name is Oleksandr Olashyn. I am a Microsoft Business Application MVP, MCT, certified Dynamics 365 Architect with passion for coding and dancing.

# Contact links
website: "www.dancingwithcrm.com" # Add your website, do not add http://
linkedin: dancingwithcrm # Add your Linkedin handle
github: oolashyn # Add your Github handle
twitter: '@dancingwithcrm'

#Social
social:
  name: Oleksandr Olashyn
  links:
    - https://www.linkedin.com/in/dancingwithcrm
    - https://github.com/oolashyn

# Newsletter
mailchimp: https://dancingwithcrm.us4.list-manage.com/subscribe/post # Add your MailChimp form identifier.

# Disqus
discus_identifier: dancingwithcrm # Add your discus identifier

# Utterances
utterances:
  repo: "OOlashyn/oolashyn.github.io"
  issue-term: "title"
  label: "Comment"
  theme: "github-dark"

# Tracker
analytics: UA-141204351-1

#Google verification
#google-site-verification: googlef755d5fd81eb0bf8.html

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-target-blank
  - jekyll-sass-converter

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
